export const regions = [
    'Blagoevgrad',
    'Burgas',	
    'Dobrich',
    'Gabrovo',
    'Haskovo',
    'Kardzhali',
    'Kyustendil',
    'Lovech',
    'Montana',
    'Pazardzhik',
    'Pernik',
    'Pleven',
    'Plovdiv',
    'Razgrad',
    'Ruse',
    'Shumen',
    'Silistra',
    'Sliven',
    'Smolyan',
    'Sofia City',
    'Sofia Province',
    'Stara Zagora',
    'Targovishte',
    'Varna',
    'Veliko Tarnovo',
    'Vidin',
    'Vratsa',
    'Yambol'
]